project_id = "uqnwhypjrisbfkouwcge"

[functions.meal-suggest]
verify_jwt = false

[functions.diary-summary]
verify_jwt = false

[functions.recipe-generate]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true
