// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-meals.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.1";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const key = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY",
    "SUPABASE_ANON_KEY",
    "VITE_SUPABASE_ANON_KEY"
  ]);
  if (!key) {
    throw new Error("SUPABASE_PUBLISHABLE_KEY (or SUPABASE_ANON_KEY) is required");
  }
  return key;
}
function supabaseForUser(ctx) {
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-meals.ts
var list_meals_default = defineTool({
  name: "list_meals",
  title: "List meals",
  description: "List the signed-in user's logged meals with calories and macros, optionally filtered by date range (YYYY-MM-DD).",
  inputSchema: {
    from: z.string().optional().describe("Start date, YYYY-MM-DD."),
    to: z.string().optional().describe("End date, YYYY-MM-DD."),
    limit: z.number().int().optional().describe("Max rows to return (default 50, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 50, 1), 200);
    let query = supabaseForUser(ctx).from("meals").select("id,name,calories,protein,carbs,fat,fiber,sugar,category,eaten_at,health_score").order("eaten_at", { ascending: false }).limit(max);
    if (from) query = query.gte("eaten_at", `${from}T00:00:00.000Z`);
    if (to) query = query.lte("eaten_at", `${to}T23:59:59.999Z`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { meals: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-meal.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^3.25.76";
var log_meal_default = defineTool2({
  name: "log_meal",
  title: "Log a meal",
  description: "Log a meal with calories and macros for the signed-in user.",
  inputSchema: {
    name: z2.string().trim().describe("Meal name, e.g. 'Chicken salad'."),
    calories: z2.number().describe("Total calories (kcal) for the portion."),
    protein: z2.number().optional().describe("Protein in grams."),
    carbs: z2.number().optional().describe("Carbohydrates in grams."),
    fat: z2.number().optional().describe("Fat in grams."),
    category: z2.string().optional().describe("Meal category, e.g. breakfast, lunch, dinner, snack."),
    eaten_at: z2.string().optional().describe("ISO timestamp of when it was eaten. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const name = input.name.trim();
    if (!name) return { content: [{ type: "text", text: "Meal name is required" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("meals").insert({
      user_id: ctx.getUserId(),
      name: name.slice(0, 120),
      calories: Math.max(0, Math.round(input.calories)),
      protein: Math.max(0, input.protein ?? 0),
      carbs: Math.max(0, input.carbs ?? 0),
      fat: Math.max(0, input.fat ?? 0),
      category: input.category ?? null,
      ...input.eaten_at ? { eaten_at: input.eaten_at } : {}
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged "${name}" (${input.calories} kcal).` }],
      structuredContent: { meal: data }
    };
  }
});

// src/lib/mcp/tools/get-daily-summary.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^3.25.76";
var get_daily_summary_default = defineTool3({
  name: "get_daily_summary",
  title: "Get daily summary",
  description: "Summarize the signed-in user's nutrition for one day: total calories, macros, water intake and workouts.",
  inputSchema: {
    date: z3.string().optional().describe("Day in YYYY-MM-DD format. Defaults to today (UTC).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const day = date ?? (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const supabase = supabaseForUser(ctx);
    const [meals, water, workouts] = await Promise.all([
      supabase.from("meals").select("name,calories,protein,carbs,fat").gte("eaten_at", `${day}T00:00:00.000Z`).lte("eaten_at", `${day}T23:59:59.999Z`),
      supabase.from("water_logs").select("ml").eq("day", day).maybeSingle(),
      supabase.from("workouts").select("name,minutes,calories_burned").gte("performed_at", `${day}T00:00:00.000Z`).lte("performed_at", `${day}T23:59:59.999Z`)
    ]);
    const error = meals.error ?? workouts.error;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = meals.data ?? [];
    const sum = (key) => Math.round(rows.reduce((a, r) => a + (Number(r[key]) || 0), 0));
    const summary = {
      date: day,
      meals: rows.length,
      calories: sum("calories"),
      protein_g: sum("protein"),
      carbs_g: sum("carbs"),
      fat_g: sum("fat"),
      water_ml: water.data?.ml ?? 0,
      workouts: (workouts.data ?? []).length,
      calories_burned: Math.round(
        (workouts.data ?? []).reduce((a, w) => a + (Number(w.calories_burned) || 0), 0)
      )
    };
    return {
      content: [{ type: "text", text: JSON.stringify(summary) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/tools/log-weight.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z4 } from "npm:zod@^3.25.76";
var log_weight_default = defineTool4({
  name: "log_weight",
  title: "Log weight",
  description: "Record a body-weight entry (kg) for the signed-in user.",
  inputSchema: {
    weight_kg: z4.number().describe("Body weight in kilograms."),
    logged_at: z4.string().optional().describe("ISO timestamp. Defaults to now.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ weight_kg, logged_at }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!(weight_kg > 0) || weight_kg > 500) {
      return { content: [{ type: "text", text: "weight_kg must be between 0 and 500" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("weights").insert({
      user_id: ctx.getUserId(),
      weight_kg,
      ...logged_at ? { logged_at } : {}
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Logged weight ${weight_kg} kg.` }],
      structuredContent: { weight: data }
    };
  }
});

// src/lib/mcp/tools/list-weights.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_weights_default = defineTool5({
  name: "list_weights",
  title: "List weight entries",
  description: "List the signed-in user's recorded body-weight entries, newest first.",
  inputSchema: {
    limit: z5.number().int().optional().describe("Max rows to return (default 30, max 200).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const max = Math.min(Math.max(limit ?? 30, 1), 200);
    const { data, error } = await supabaseForUser(ctx).from("weights").select("id,weight_kg,logged_at").order("logged_at", { ascending: false }).limit(max);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { weights: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uqnwhypjrisbfkouwcge";
var mcp_default = defineMcp({
  name: "scaniq",
  title: "ScanIQ",
  version: "0.1.0",
  instructions: "Tools for ScanIQ, a calorie and nutrition tracker. Use `get_daily_summary` for a day's totals, `list_meals` to read logged meals, `log_meal` to add a meal with calories and macros, and `log_weight` / `list_weights` for body weight. All tools act on the signed-in user's own data.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_daily_summary_default, list_meals_default, log_meal_default, log_weight_default, list_weights_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
